# Write your code here :-)
print("======================")
print("| Best Friend Maker  |")
print("| by Isaac Finkbeiner|")
print("======================")
print("")
print("Hi, I'm the computer")
name = input("What is your name? ")
print(f"Hello {name}")
color = input("What is your favorite color? ")
print(f"No Way! My favorite color is also {color}! ")
movie = input("What is your favorite movie? ")
print(f"WHAT!?! My favorite movie is also {movie}!")
game = input("What is your favorite game? ")
print(f"Get out of here! My favorite game is {game}, too! ")
print("We like the same things! We should be best friends! ")
input("How much wood can a woodchuck chuck if a woodchuck couln't chuck wood? ")
print("WOW!")